version: 0.2

env:
  secrets-manager:
    # Secret will be assigned to env var name 'ENV'
    ENV: dev/strapi

phases:
  install:
    commands:
      # Writing env var to .env file
      - echo "$ENV" > apps/nk-associates-cms/.env
      - echo "Installing source NVM"
      - node -v
      - npm -v
      - echo "Installing dependencies"
      - npm install -g yarn
      - yarn install

  build:
    commands:
      - echo "Building the Strapi application"
      - cd apps/nk-associates-cms/src/plugins/select
      - yarn install
      - yarn build
      - cd ../../../..
      - yarn turbo build --filter=nk-associates-cms

artifacts:
  files:
    - '**/*'