version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  pre_build:
    commands:
      - npm run build
  build:
    commands:
      - echo Build started on `date`
      - npm run start
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
