import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'


const metropolis = localFont({
  src: './assets/fonts/Metropolis-Regular.otf',
  variable: '--font-metroplis',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={metropolis.className}>{children}</body>
    </html>
  )
}
